
[tool.ruff]
line-length = 120
indent-width = 4
target-version = py312
extend-exclude = [migrations, **/local_settings.py]

[tool.ruff.lint]
select = [E, F, W, I, S, B]
ignore = [S608]

[tool.ruff.format]
quote-style = double
indent-style = space
skip-magic-trailing-comma = false
line-ending = auto
docstring-code-line-length = dynamic

[tool.ruff.lint.isort]
case-sensitive = true

